### ISSUE TITLE
Publish patch release of 1602/elm-feather with updated README?

### ISSUE THREAD

**Issue by ianmackenzie** [feathericons/elm-feather#15]
It would be useful to publish a patch version of `1602/elm-feather` with a note at the top of the README mentioning that (at least for now) this repository should be used instead. This would help ensure that people who find `1602/elm-feather` on the Elm package website (as I did, when I was checking to see if it had been updated to 0.19) would immediately see that they should be using a different package. (I realize that a note has been added to the README on GitHub, but without a patch release it doesn't show up on the package web site.)

Thanks for your work on this package, and especially for putting in the extra time to make a fork to work around the compiler bug!

**Comment by 1602** [comment]
Done! Thanks for the nudge, this is indeed confusing when documentation doesn't explain what's going on. I hope it's more clear now: https://package.elm-lang.org/packages/1602/elm-feather/2.3.5/

As for the future, package will remain in feathericons organisation, since this is a better fit, not just because of the compiler issue.

**Comment by ianmackenzie** [comment]
Thanks! And yeah, that makes sense.
